version: '3'
services:
  node-bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.node-bot.entrypoints=web"
      - "traefik.http.routers.node-bot.rule=Host(`${host_url}`) && PathPrefix(`/`)"
      - "traefik.http.services.node-bot.loadbalancer.server.port=${PORT}"
      - "traefik.http.routers.node-bot.priority=1"
      - "traefik.http.routers.node-bot.tls.certresolver=le" 
      - "traefik.http.routers.node-bot.entrypoints=https" 
    networks:
      - traefik

networks:
  traefik:
    name: traefik
    external: true